In [2]:
import numpy as np
import pandas as pd

In [5]:
data = {
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, 6, np.nan]
}

print(data)
df1 = pd.DataFrame(data)
print(df1)

{'A': [1, 2, nan, 4], 'B': [5, nan, 6, nan]}
     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  6.0
3  4.0  NaN

In [7]:
df1.isna().sum()

A    1
B    2
dtype: int64

In [8]:
df1.isna().any()

A    True
B    True
dtype: bool

In [9]:
df1.dropna()

     A    B
0  1.0  5.0

In [11]:
df1.dropna(thresh= 2)

     A    B
0  1.0  5.0

In [12]:
df1

     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  6.0
3  4.0  NaN

In [13]:
df1.fillna(2)

     A    B
0  1.0  5.0
1  2.0  2.0
2  2.0  6.0
3  4.0  2.0

In [14]:
 df1

     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  6.0
3  4.0  NaN

In [15]:
values = {'A': 300, 'B': 1200}
df1.fillna(value= values)

       A       B
0    1.0     5.0
1    2.0  1200.0
2  300.0     6.0
3    4.0  1200.0