In [1]:
import pandas as pd
import numpy as np

In [2]:
labels = ['a', 'b', 'c']
list1 = [2, 3 ,4]

In [3]:
pd.Series(list1, index=labels)

a    2
b    3
c    4
dtype: int64

In [4]:
data = {
    'name': ["Gourav", "Home", "Lens"],
    'Age': [23, 999, 28],
    'marks': [45, 67, 89]
}

In [5]:
DF1 = pd.DataFrame(data)

In [6]:
DF1

     name  Age  marks
0  Gourav   23     45
1    Home  999     67
2    Lens   28     89

In [19]:
list1 = [45, 67, 78]
DF2 = pd.DataFrame(list1)
DF2

    0
0  45
1  67
2  78

In [20]:
list2 = [
    [45, 67, 78],
    [123, 456, 789],
    [1234, 5678, 9012]
]
DF3 = pd.DataFrame(list2)
DF3

      0     1     2
0    45    67    78
1   123   456   789
2  1234  5678  9012

In [22]:
list3 =  [
    ["Gourav", 34, "Shivani"],
    ["Homelander", 56, "Shiva"]
]

DF4 = pd.DataFrame(list3)
DF4

            0   1        2
0      Gourav  34  Shivani
1  Homelander  56    Shiva

In [23]:
columns = ["Name", "Marks", "Alias"]
DF5 = pd.DataFrame(list3, columns = columns)
DF5

         Name  Marks    Alias
0      Gourav     34  Shivani
1  Homelander     56    Shiva

In [24]:
DF5

         Name  Marks    Alias
0      Gourav     34  Shivani
1  Homelander     56    Shiva

In [28]:
DF5["Name"]

0        Gourav
1    Homelander
Name: Name, dtype: object

In [32]:
DF5[["Name", "Marks"]]

         Name  Marks
0      Gourav     34
1  Homelander     56

In [35]:
DF5

         Name  Marks    Alias
0      Gourav     34  Shivani
1  Homelander     56    Shiva

In [36]:
DF5["Domain"] = ['QEA', 'DEV']
DF5

         Name  Marks    Alias Domain
0      Gourav     34  Shivani    QEA
1  Homelander     56    Shiva    DEV

In [41]:
DF5.drop("Marks", axis=1)

         Name    Alias Domain
0      Gourav  Shivani    QEA
1  Homelander    Shiva    DEV

In [42]:
DF5

         Name  Marks    Alias Domain
0      Gourav     34  Shivani    QEA
1  Homelander     56    Shiva    DEV

In [43]:
DF5.drop("Marks", axis= 1, inplace=True)

In [44]:
DF5

         Name    Alias Domain
0      Gourav  Shivani    QEA
1  Homelander    Shiva    DEV

In [47]:
 DF5[["Designation", "Salary"]] = [["Engineering", "30k"],["Doctor","40k"]]

In [48]:
DF5

         Name    Alias Domain  Designation Salary
0      Gourav  Shivani    QEA  Engineering    30k
1  Homelander    Shiva    DEV       Doctor    40k

In [49]:
DF5.drop(["Alias","Domain"], axis=1)

         Name  Designation Salary
0      Gourav  Engineering    30k
1  Homelander       Doctor    40k

In [50]:
DF5.loc[0]

Name                Gourav
Alias              Shivani
Domain                 QEA
Designation    Engineering
Salary                 30k
Name: 0, dtype: object

In [51]:
DF5.loc(0)

In [52]:
List1 = [56, 45, 90]
series1 = pd.Series(List1)

In [53]:
series1

0    56
1    45
2    90
dtype: int64

In [57]:
labels2 = ['A', 'B', 'C']
serie2 = pd.Series(List1, index=labels2)

In [55]:
List1

[56, 45, 90]

In [56]:
series1

0    56
1    45
2    90
dtype: int64

In [58]:
serie2

A    56
B    45
C    90
dtype: int64

In [60]:
dataFrame1 = {
    "Name": ['Gourav', 'Singh', 'Dosad'],
    "Age": [21, 22, 23],
    "Marks": [45, 56, 67]
}

dataFrame2 = pd.DataFrame(dataFrame1)

In [64]:
pd.DataFrame(dataFrame2, index=labels2)

  Name  Age  Marks
A  NaN  NaN    NaN
B  NaN  NaN    NaN
C  NaN  NaN    NaN

In [63]:
pd.DataFrame(dataFrame1, index=labels2)

     Name  Age  Marks
A  Gourav   21     45
B   Singh   22     56
C   Dosad   23     67

In [65]:
List3 = [
    [34, 45],
    [56, 67],
    [78, 89]
]
dataFrame3 = pd.DataFrame(List3)

In [66]:
dataFrame3

    0   1
0  34  45
1  56  67
2  78  89

In [67]:
col = ["ran1", "ran2"]
pd.DataFrame(List3, columns= col)

   ran1  ran2
0    34    45
1    56    67
2    78    89

In [69]:
dataFrame2

     Name  Age  Marks
0  Gourav   21     45
1   Singh   22     56
2   Dosad   23     67

In [72]:
dataFrame2["Name"]

0    Gourav
1     Singh
2     Dosad
Name: Name, dtype: object

In [73]:
dataFrame2["Name"][1]

'Singh'

In [74]:
dataFrame2[["Name", "Marks"]]

     Name  Marks
0  Gourav     45
1   Singh     56
2   Dosad     67

In [75]:
dataFrame2

     Name  Age  Marks
0  Gourav   21     45
1   Singh   22     56
2   Dosad   23     67

In [76]:
dataFrame2["city"] = ["Kolkata", "Chennai", "Haldwani"]

In [77]:
dataFrame2

     Name  Age  Marks      city
0  Gourav   21     45   Kolkata
1   Singh   22     56   Chennai
2   Dosad   23     67  Haldwani

In [80]:
dataFrame2[["Contact", "Marks"]] = pd.DataFrame({
    "Contact" : [1234, 5678, 9012],
    "Marks" : [456, 56, 67]
})

dataFrame2

     Name  Age  Marks      city  Contact
0  Gourav   21    456   Kolkata     1234
1   Singh   22     56   Chennai     5678
2   Dosad   23     67  Haldwani     9012

In [84]:
dataFrame2.drop("Contact", axis=1, inplace=True)

In [85]:
dataFrame2

     Name  Age  Marks      city
0  Gourav   21    456   Kolkata
1   Singh   22     56   Chennai
2   Dosad   23     67  Haldwani

In [86]:
dataFrame2[["Contact", "IQ"]] = [[1234, 89], [5678, 90], [9012, 91]]

In [87]:
dataFrame2

     Name  Age  Marks      city  Contact  IQ
0  Gourav   21    456   Kolkata     1234  89
1   Singh   22     56   Chennai     5678  90
2   Dosad   23     67  Haldwani     9012  91

In [88]:
dataFrame2.loc[2]

Name          Dosad
Age              23
Marks            67
city       Haldwani
Contact        9012
IQ               91
Name: 2, dtype: object

In [89]:
dataFrame2.loc[[0,2]]

     Name  Age  Marks      city  Contact  IQ
0  Gourav   21    456   Kolkata     1234  89
2   Dosad   23     67  Haldwani     9012  91

In [92]:
dataFrame2

     Name  Age  Marks      city  Contact  IQ
0  Gourav   21    456   Kolkata     1234  89
1   Singh   22     56   Chennai     5678  90
2   Dosad   23     67  Haldwani     9012  91

In [91]:
dataFrame3

  Name  Age  Marks city  Contact  IQ
A  NaN  NaN    NaN  NaN      NaN NaN
B  NaN  NaN    NaN  NaN      NaN NaN
C  NaN  NaN    NaN  NaN      NaN NaN

In [93]:
dataFrame4 = pd.read_csv('data.csv')

In [94]:
print(dataFrame4)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [95]:
print(dataFrame4.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [97]:
dataFrame2

     Name  Age  Marks      city  Contact  IQ
0  Gourav   21    456   Kolkata     1234  89
1   Singh   22     56   Chennai     5678  90
2   Dosad   23     67  Haldwani     9012  91

In [98]:
dataFrame2.loc[[0, 1]][["city", "Contact"]]

      city  Contact
0  Kolkata     1234
1  Chennai     5678

In [100]:
dataFrame2[dataFrame2["Age"] > 21]

    Name  Age  Marks      city  Contact  IQ
1  Singh   22     56   Chennai     5678  90
2  Dosad   23     67  Haldwani     9012  91

In [102]:
dataFrame2[(dataFrame2["Age"] > 21)  & (dataFrame2["city"] == "Haldwani")]

    Name  Age  Marks      city  Contact  IQ
2  Dosad   23     67  Haldwani     9012  91