In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2],
    'B': [3, 4]
})

In [3]:
df2 = pd.DataFrame({
    'A': [5, 7],
    'B': [8, 9]
})

In [4]:
pd.concat([df1, df2])

   A  B
0  1  3
1  2  4
0  5  8
1  7  9

In [5]:
df3 = pd.DataFrame({
    'A': [1, 2],
    'B': [3, 4]
})

In [6]:
df4 = pd.DataFrame({
    'C': [1, 2],
    'D': [3, 4]
})

In [7]:
pd.concat([df3, df4])

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  1.0  3.0
1  NaN  NaN  2.0  4.0

In [8]:
 # Joining 2 DataFrames

df5 = pd.DataFrame({
    'A': ["Gourav", "Bob", "Mice"]
}, index=[1, 2, 3])

df6 = pd.DataFrame({
    'score': [45, 89, 56]
}, index= [2, 3, 4])

In [9]:
df5

        A
1  Gourav
2     Bob
3    Mice

In [10]:
df6

   score
2     45
3     89
4     56

In [11]:
df5.join(df6)

        A  score
1  Gourav    NaN
2     Bob   45.0
3    Mice   89.0

In [12]:
df6.join(df5)

   score     A
2     45   Bob
3     89  Mice
4     56   NaN

In [13]:
df5.join(df6, how= "outer")

        A  score
1  Gourav    NaN
2     Bob   45.0
3    Mice   89.0
4     NaN   56.0

In [44]:
# Group BY

df7 = pd.DataFrame({
    'category': ['A', 'B', 'A', 'B', 'C'],
    "sales": [12000, 8900, 12000, 230, 12000],
    "hike": [1000, 3000, 1000, 3000, 2000]
})

In [28]:
df7

  category  sales  hike
0        A  45000  1000
1        B   8900  3000
2        A  12000  1000
3        B    230  3000
4        C  10000  2000

In [30]:
df8 = df7.groupby("category")

In [31]:
for a, b in df8:
    print(a)
    print(b)

A
  category  sales  hike
0        A  45000  1000
2        A  12000  1000
B
  category  sales  hike
1        B   8900  3000
3        B    230  3000
C
  category  sales  hike
4        C  10000  2000

In [35]:
df7.groupby("category")['sales'].sum()
df9 = df7.groupby('hike')

In [37]:
for i, v in df9:
    print(i)
    print(v)

1000
  category  sales  hike
0        A  45000  1000
2        A  12000  1000
2000
  category  sales  hike
4        C  10000  2000
3000
  category  sales  hike
1        B   8900  3000
3        B    230  3000

In [39]:
df9['sales'].sum()

hike
1000    57000
2000    10000
3000     9130
Name: sales, dtype: int64

In [45]:
df10 = df7.groupby(['category', 'sales'])['hike'].sum()
df10

category  sales
A         12000    2000
B         230      3000
          8900     3000
C         12000    2000
Name: hike, dtype: int64

In [46]:
df7['sales'].mean()

np.float64(9026.0)

In [47]:
df7['sales'].mode()

0    12000
Name: sales, dtype: int64

In [48]:
df7

  category  sales  hike
0        A  12000  1000
1        B   8900  3000
2        A  12000  1000
3        B    230  3000
4        C  12000  2000

In [49]:
df7['hike'].mode()

0    1000
1    3000
Name: hike, dtype: int64

In [50]:
df7['hike'].median()

2000.0

In [51]:
 df7['sales'].count()

np.int64(5)

In [52]:
df7.count()

category    5
sales       5
hike        5
dtype: int64

In [54]:
df7['sales'].agg(['mean', 'median', 'max', 'min'])

mean       9026.0
median    12000.0
max       12000.0
min         230.0
Name: sales, dtype: float64