In [2]:
import numpy as np
import pandas as pd

In [3]:
Employees = {
    'Employee_ID': [1, 2, 3],
    'Name': ["Gourav", "Homelander", "Lenslander"],
    'Department': ['HR', 'IT', 'Sales']
}

In [4]:
Salaries = {
    'Employee_ID': [1, 4, 3],
    'Salary': [60000, 50000, 230000],
    'Bonus': [2000, 3000, 2000]
}

In [5]:
emp = pd.DataFrame(Employees)

In [6]:
sal = pd.DataFrame(Salaries)

In [7]:
emp

   Employee_ID        Name Department
0            1      Gourav         HR
1            2  Homelander         IT
2            3  Lenslander      Sales

In [8]:
sal

   Employee_ID  Salary  Bonus
0            1   60000   2000
1            4   50000   3000
2            3  230000   2000

In [9]:
pd.merge(emp, sal)

   Employee_ID        Name Department  Salary  Bonus
0            1      Gourav         HR   60000   2000
1            3  Lenslander      Sales  230000   2000

In [10]:
pd.merge(emp, sal, on="Employee_ID", how="outer")

   Employee_ID        Name Department    Salary   Bonus
0            1      Gourav         HR   60000.0  2000.0
1            2  Homelander         IT       NaN     NaN
2            3  Lenslander      Sales  230000.0  2000.0
3            4         NaN        NaN   50000.0  3000.0